
services:
  web:
    image: express-docker:01 
    container_name: express-docker-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  
    volumes:
      - .:/app  # Optional: Mount your current directory to the /app directory in the container
    restart: always  # Automatically restart the container if it stops
