
services:
  app:
    image: express-docker:01 
    container_name: express-docker-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  
    volumes:
      - .:/app 
      - /app/node_modules  